### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pallavsen007** [noscript/elevator.vim#1]
Error detected while processing /home/user/.vim/bundle/elevator.vim/plugin/elevator.vim:
line    1:
E683: File name missing or invalid pattern
Pattern not found: elevator_loaded = true
line    8:
E492: Not an editor command: import autoload 'elevator.vim'
line   11:
E216: No such group or event: WinScrolled * elevator#Show(expand('<amatch>')->str2nr())

**Comment by noscript** [comment]
`WinScrolled` has been added in [Vim 8.2.4713](https://github.com/vim/vim/commit/0937182d49fa8db50cec42785f22f1031760a0bd).
